name: Deploy to Yandex Cloud Function

on:
  push:
    branches:
      - main
      - develop 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install make
        run: sudo apt-get install make 

      - name: Build
        run: |
          go build -o bin/main ./cmd/...  # Сборка проекта и помещение исполняемого файла в bin/main

      - name: Install Yandex CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:/usr/local/bin

      - name: Deploy
        env:
          YC_TOKEN: ${{ secrets.AUTHORIZED_KEY }}
        run: |
          yc config set token $YC_TOKEN
          yc serverless function version create \
            --function-name d4enifnsdldib6q5d8pa \
            --runtime go113 \
            --entrypoint main \
            --memory 256m \
            --execution-timeout 5s \
            --source-path ./bin/main
          # Публикация версии функции
          yc serverless function version publish \
            --function-name d4enifnsdldib6q5d8pa

      - name: Deploy to Yandex Cloud Function
        run: |
          yc init --token ${{ secrets.YANDEX_TOKEN }}
          yc config profile create github-actions
          yc config set folder-id ${{ secrets.YANDEX_FOLDER_ID }}
          yc config set token ${{ secrets.YANDEX_TOKEN }}
          yc config set cloud-id ${{ secrets.YANDEX_CLOUD_ID }}
          yc serverless function version create \
              --function-name wtf2 \
              --runtime golang113 \
              --source-path main-go.zip \
              --entrypoint main.Handler \
              --format json | jq -r '.id'
          yc serverless function version set-tag \
              --id $version_id \
              --tag public
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}

