name: Deploy to Yandex Cloud Function

on:
  push:
    branches:
      - main
      - develop 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install make
        run: sudo apt-get install make  # Установка make, если еще не установлен

      - name: Build
        run: |
          go build -o bin/main ./cmd/...  # Сборка проекта и помещение исполняемого файла в bin/main

      - name: Install yc-cli
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | sudo bash
          echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV
      - name: Deploy
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
          YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}
        run: |
          yc config set token $YANDEX_TOKEN
          yc config set folder-id $YANDEX_FOLDER_ID
          yc config set cloud-id $YANDEX_CLOUD_ID
          yc serverless function version create \
            --function-name wtf2 \
            --runtime go113 \
            --entrypoint main \
            --memory 256m \
            --execution-timeout 5s \
            --source-path ./main-go.zip
          # Публикация версии функции
          yc serverless function version publish \
            --function-name wtf2
