name: Deploy to Yandex Cloud Function

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  

      - name: Install make
        run: sudo apt-get install make  # Установка make, если еще не установлен

      - name: Build
        run: make build  # Вызов команды сборки из Makefile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up yc-cli
        uses: yandex-cloud/yc-cli-action@v1
        with:
          yc-token: y0_AgAAAAAXBtATAATuwQAAAAEAG_rLAAChm-kV2qBHyLjAgwKtv43dr_yZ7Q

      - name: Build and deploy
        run: |
          # Сборка и подготовка кода (если необходимо)
          # Например, компиляция Go-кода
          go build -o my-function main.go

          # Деплой функции в Yandex Cloud
          yc serverless function version create \
            --function-name my-function \
            --runtime go113 \
            --entrypoint my-function \
            --memory 256m \
            --execution-timeout 5s \
            --source-path ./my-function

          # Публикация версии функции
          yc serverless function version publish \
            --function-name my-function

      - name: Show deployment status
        run: |
          # Вывод статуса деплоя (по желанию)
          yc serverless function version list \
            --function-name my-function
