name: Deploy to Yandex Cloud Function

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install make
        run: sudo apt-get install make  # Установка make, если еще не установлен

      - name: Build
        run: |
          mkdir -p bin  # Создаем папку bin, если ее еще нет
          go build -o bin/main ./cmd/...  # Сборка проекта и помещение исполняемого файла в bin/main

      - name: Install yc-cli
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Deploy
        run: |
          # Деплой функции в Yandex Cloud
          /root/.yandex-cloud/bin/yc serverless function version create \
            --function-name d4enifnsdldib6q5d8pa \
            --runtime go113 \
            --entrypoint main \
            --memory 256m \
            --execution-timeout 5s \
            --source-path ./bin/main  # Указываем путь к исполняемому файлу в папке bin/main

          # Публикация версии функции
          /root/.yandex-cloud/bin/yc serverless function version publish \
            --function-name d4enifnsdldib6q5d8pa

      - name: Show deployment status
        run: |
          # Вывод статуса деплоя (по желанию)
          /root/.yandex-cloud/bin/yc serverless function version list \
            --function-name d4enifnsdldib6q5d8pa
