name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run tests
        run: |
          echo "Running tests"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o bin/myapp cmd/main.go

      - name: Run unit tests
        run: go test -v ./...

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-binary
          path: bin/myapp

