name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o bin/myapp cmd/main.go

      - name: Run unit tests
        run: go test -v ./...

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-binary 
          path: bin/myapp

      - name: Deploy to Yandex Cloud Functions
        run: |
          curl -X POST \
            -H "Authorization: Bearer $YANDEX_CLOUD_API_TOKEN" \
            -F "file=@bin/myapp" \
            -F "function_id=$YANDEX_CLOUD_FUNCTION_ID" \
            https://functions.yandexcloud.net/api/v1/functions/upload

